# Generated by Django 5.2.4 on 2026-07-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization_id",
                    models.IntegerField(
                        db_index=True,
                        default=None,
                        help_text="ID da organização no sistema de autenticação",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.CharField(
                        blank=True, db_index=True, max_length=14, null=True
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "email",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("saved", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Contato",
                "verbose_name_plural": "Contatos",
                "unique_together": {("organization_id", "email", "document")},
            },
        ),
    ]
