# Generated by Django 5.2.4 on 2026-07-14 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inspection", "0011_inspectiontype_provider_inspector"),
        ("message", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HinovaToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization_id",
                    models.IntegerField(
                        db_index=True,
                        default=None,
                        help_text="ID da organização no sistema de autenticação",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("usuario", models.CharField(max_length=32)),
                ("senha", models.CharField(max_length=32)),
                ("has_activator", models.BooleanField(default=False)),
                (
                    "api_token",
                    models.CharField(blank=True, max_length=192, null=True),
                ),
                (
                    "token_usuario",
                    models.CharField(blank=True, max_length=288, null=True),
                ),
                (
                    "token_painel",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "last_sync_terms",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "last_sync_situation_motivo",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "Token Hinova",
                "verbose_name_plural": "Tokens Hinova",
            },
        ),
        migrations.CreateModel(
            name="VehicleSGA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization_id",
                    models.IntegerField(
                        db_index=True,
                        default=None,
                        help_text="ID da organização no sistema de autenticação",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plate",
                    models.CharField(blank=True, max_length=17, null=True),
                ),
                (
                    "chassi",
                    models.CharField(blank=True, max_length=17, null=True),
                ),
                (
                    "codigo_veiculo",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "codigo_evento",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "inspection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_sga",
                        to="inspection.inspection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Veículo SGA",
                "verbose_name_plural": "Veículos SGA",
            },
        ),
        migrations.CreateModel(
            name="Associate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization_id",
                    models.IntegerField(
                        db_index=True,
                        default=None,
                        help_text="ID da organização no sistema de autenticação",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "codigo_beneficiario",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("codigo_associado", models.CharField(max_length=10)),
                (
                    "contact",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="associate",
                        to="message.contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "Associado",
                "verbose_name_plural": "Associados",
                "unique_together": {
                    ("organization_id", "codigo_associado"),
                    ("organization_id", "codigo_beneficiario"),
                    ("organization_id", "contact"),
                },
            },
        ),
    ]
