"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
import sys
from pathlib import Path

import sentry_sdk
from corsheaders.defaults import default_headers
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

SECRET_KEY = config("SECRET_KEY")

DEBUG = config("DEBUG", default=False, cast=bool)
CUSTOM_TEST_SETTING = config("CUSTOM_TEST_SETTING", default=False, cast=bool)

PRODUCTION = config("PRODUCTION", default=True, cast=bool)

SENTRY_ENABLED = config("SENTRY", default=False, cast=bool)

if PRODUCTION and SENTRY_ENABLED:
    sentry_sdk.init(
        dsn="https://3f29c6ab23db52c1995ddc461e6e0b72@o4509549203619840.ingest.us.sentry.io/4510499473850368",
        send_default_pii=True,
    )


ALLOWED_HOSTS = ["*"]

DEFAULT_HTTP_PROTOCOL = "http"

DEFAULT_BCC_EMAIL = "feedback@mw-visto.com.br"

SPECTACULAR_SETTINGS = {
    "TITLE": "MW Visto API",
    "DESCRIPTION": "API do MW Visto",
    "VERSION": "1.0.0",
    "SERVE_PERMISSIONS": ["rest_framework.permissions.IsAdminUser"],
}

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "shared_auth",
    "drf_spectacular",
    "django_filters",
    "message",
    "sga",
    "inspection",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "core.observability.middleware.PerformanceMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "shared_auth.middleware.RequireAuthMiddleware",
    "shared_auth.middleware.SharedAuthMiddleware",
    "shared_auth.middleware.OrganizationMiddleware",
]

DATABASE_ROUTERS = ["shared_auth.router.SharedAuthRouter"]

ROOT_URLCONF = "core.urls"

CSRF_TRUSTED_ORIGINS = config("ORIGINS", default="").split(",")

CORS_ALLOWED_ORIGINS = config("ORIGINS", default="").split(",")

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

# Configuração opcional para permitir todos os métodos HTTP
CORS_ALLOW_ALL_METHODS = True

# Lista específica de cabeçalhos permitidos, incluindo X-Organization

CORS_ALLOW_HEADERS = list(default_headers) + ["X-Organization", "ApiKey"]

# Configuração opcional para permitir credenciais (cookies, cabeçalhos de autorização) através do CORS
CORS_ALLOW_CREDENTIALS = True

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": config("DB_ENGINE", default="django.db.backends.postgresql"),
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER", default=None),
        "PASSWORD": config("DB_PASSWORD", default=None),
        "HOST": config("DB_HOST", default=None),
        "PORT": config("DB_PORT", default="5432"),  # Porta padrão do PostgreSQL
    },
    "auth_db": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("AUTH_DB_NAME"),
        "USER": config("AUTH_DB_USER"),
        "PASSWORD": config("AUTH_DB_PASSWORD"),
        "HOST": config("AUTH_DB_HOST"),
        "PORT": config("AUTH_DB_PORT", default="5432"),
    },
}

PAGE_SIZE = 10

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "shared_auth.authentication.SharedTokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend"
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
        "rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly",
    ],
    "PAGE_SIZE": PAGE_SIZE,
}

AUTH_USER_MODEL = "shared_auth.User"

FRONT_END = config("FRONT_END") if not DEBUG else "http://localhost:3000"

ACCOUNT_EMAIL_VERIFICATION = "mandatory"  # Confirmação de email obrigatória
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = "username"
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 1  # Link expira em 1 dia
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = (
    False  # Não faz login automático após confirmação
)
ACCOUNT_CONFIRM_EMAIL_ON_GET = True  # Permite confirmação via GET request

EMAIL_BACKEND = config(
    "EMAIL_BACKEND", default="django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_HOST = config("EMAIL_HOST")
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
EMAIL_PORT = config("EMAIL_PORT")
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")

TWILIO_ACCOUNT_SID = config("TWILIO_ACCOUNT_SID", default=None)
TWILIO_AUTH_TOKEN = config("TWILIO_AUTH_TOKEN", default=None)
TWILIO_SMS_FROM = config("TWILIO_SMS_FROM", default=None)
TWILIO_WHATSAPP_FROM = config("TWILIO_WHATSAPP_FROM", default=None)
TWILIO_CONTENT_SIDS = {
    "charge_signature": {
        "whatsapp": config(
            "TWILIO_WHATSAPP_CONTENT_SID_CHARGE_SIGNATURE", default=None
        ),
    },
    "final_document": {
        "whatsapp": config(
            "TWILIO_WHATSAPP_CONTENT_SID_FINAL_DOCUMENT", default=None
        ),
    },
    "authentication_code": {
        "whatsapp": config(
            "TWILIO_WHATSAPP_CONTENT_SID_AUTHENTICATION_CODE", default=None
        ),
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

IS_TESTING = len(sys.argv) > 1 and sys.argv[1] == "test"

# Django Debug Toolbar settings
if DEBUG and not IS_TESTING:
    INSTALLED_APPS += ["debug_toolbar"]
    MIDDLEWARE += ["debug_toolbar.middleware.DebugToolbarMiddleware"]

    DEBUG_TOOLBAR_CONFIG = {
        "SHOW_TOOLBAR_CALLBACK": lambda request: True,
    }

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

CLOUDFRONT_DOMAIN = config("CLOUDFRONT_DOMAIN", default="")
CUSTOM_DOMAIN_AUTH = config("CUSTOM_DOMAIN_AUTH", default="")
AWS_STORAGE_BUCKET_NAME = config(
    "AWS_STORAGE_BUCKET_NAME", default="mw-visto-media"
)
AWS_S3_REGION_NAME = config("AWS_S3_REGION_NAME", default="sa-east-1")

if PRODUCTION:
    AWS_ACCESS_KEY_ID = config("aws_access_key_id", default=None) or None
    AWS_SECRET_ACCESS_KEY = (
        config("aws_secret_access_key", default=None) or None
    )
    AWS_SESSION_TOKEN = config("aws_session_token", default=None) or None
    AWS_PROFILE = config("AWS_PROFILE", default=None) or None
    AWS_S3_SESSION_PROFILE = AWS_PROFILE

    # Lambda Rust para processamento de PDF
    NATIVE_PDF_LAMBDA_URL = config(
        "NATIVE_PDF_LAMBDA_URL",
        default="https://ew6ge6l5kyjy7lhq5civmbqndq0ctdvy.lambda-url.sa-east-1.on.aws/",
    )

    AWS_QUERYSTRING_EXPIRE = 604800
    AWS_S3_CUSTOM_DOMAIN = f"{CLOUDFRONT_DOMAIN}"

    STATIC_URL = f"https://{CUSTOM_DOMAIN_AUTH}/static/"
    STATIC_LOCATION = "static"

    MEDIA_URL = f"https://{CLOUDFRONT_DOMAIN}/media/"
    PUBLIC_MEDIA_LOCATION = "media"

    STORAGES = {
        "staticfiles": {"BACKEND": "core.storage_backends.StaticStorage"},
        "default": {"BACKEND": "core.storage_backends.MediaStorage"},
    }

    MAX_UPLOAD_SIZE = 1024 * 1024 * 10  # 10MB
else:
    STATIC_URL = "static/"
    STATIC_ROOT = BASE_DIR / "static"

    MEDIA_ROOT = os.path.join(BASE_DIR, "media")
    MEDIA_URL = "/media/"
    DBBACKUP_STORAGE = "django.core.files.storage.FileSystemStorage"
    DBBACKUP_STORAGE_OPTIONS = {"location": "/backup/"}

HINOVA_URL = "https://api.hinova.com.br/api/sga/v2/"
ACTIVATOR_URL = config(
    "ACTIVATOR_URL", default="https://ativador.clubeautos.com.br"
)
SYSTEM_ID = 3

# Performance Observability
PERF_SAMPLE_RATE = (
    1.0 if DEBUG else config("PERF_SAMPLE_RATE", default=0.3, cast=float)
)
PERF_SLOW_REQUEST_MS = 2000
PERF_SLOW_QUERY_MS = 500
PERF_N1_THRESHOLD = 30

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {
            "()": "pythonjsonlogger.json.JsonFormatter",
            "format": "%(asctime)s %(levelname)s %(name)s %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json",
        },
    },
    "loggers": {
        "observability": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
