# Generated by Django 5.2.4 on 2026-07-08 01:30

import django.db.models.deletion
import inspection.models.step
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.IntegerField(db_index=True, default=None, help_text='ID da organização no sistema de autenticação', null=True)),
                ('user_id', models.IntegerField(db_index=True, default=None, help_text='ID do usuário no sistema de autenticação', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Data e hora em que a instância foi deletada (soft delete)', null=True, verbose_name='Deletado em')),
                ('deleted_by_id', models.IntegerField(blank=True, help_text='Usuário que deletou a instância (soft delete)', null=True, verbose_name='Deletado por')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('pending', 'Pendente'), ('in_progress', 'Em Vistoria'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('hash', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('scheduled_to', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Vistoria',
                'verbose_name_plural': 'Vistorias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, help_text='Instruções para o vistoriador realizar este passo.', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=inspection.models.step.step_photo_upload_to)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='inspection.inspection')),
            ],
            options={
                'verbose_name': 'Passo de Vistoria',
                'verbose_name_plural': 'Passos de Vistoria',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
