# Generated by Django 5.2.4 on 2026-07-08 12:30

import django.db.models.deletion
import inspection.models.inspection_type_step
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inspection", "0002_alter_inspection_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="InspectionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization_id",
                    models.IntegerField(
                        db_index=True,
                        default=None,
                        help_text="ID da organização no sistema de autenticação",
                        null=True,
                    ),
                ),
                (
                    "user_id",
                    models.IntegerField(
                        db_index=True,
                        default=None,
                        help_text="ID do usuário no sistema de autenticação",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Data e hora em que a instância foi deletada (soft delete)",
                        null=True,
                        verbose_name="Deletado em",
                    ),
                ),
                (
                    "deleted_by_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Usuário que deletou a instância (soft delete)",
                        null=True,
                        verbose_name="Deletado por",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "expiration_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "expiration_hours",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "Tipo de Vistoria",
                "verbose_name_plural": "Tipos de Vistoria",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="inspection",
            name="expiration_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inspection",
            name="expiration_hours",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inspectionstep",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("approved", "Aprovada"),
                    ("rejected", "Reprovada"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="inspection",
            name="inspection_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inspections",
                to="inspection.inspectiontype",
            ),
        ),
        migrations.CreateModel(
            name="InspectionTypeStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="Instruções para o vistoriador realizar este passo.",
                        null=True,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "instruction_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=inspection.models.inspection_type_step.type_step_photo_upload_to,
                    ),
                ),
                ("is_sequential", models.BooleanField(default=False)),
                ("allow_attachment", models.BooleanField(default=False)),
                (
                    "high_resolution",
                    models.CharField(
                        choices=[("high", "Alta"), ("low", "Baixa")],
                        default="high",
                        max_length=10,
                    ),
                ),
                (
                    "inspection_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="inspection.inspectiontype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Passo do Tipo de Vistoria",
                "verbose_name_plural": "Passos do Tipo de Vistoria",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="inspectionstep",
            name="type_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inspection.inspectiontypestep",
            ),
        ),
    ]
