# Generated by Django 5.2.4 on 2026-07-08 12:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "inspection",
            "0003_inspectiontype_inspection_expiration_days_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inspectionstep",
            name="description",
        ),
        migrations.RemoveField(
            model_name="inspectionstep",
            name="instructions",
        ),
        migrations.RemoveField(
            model_name="inspectionstep",
            name="title",
        ),
    ]
