# Generated by Django 5.2.4 on 2026-07-10 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0004_remove_inspectionstep_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionMotive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.IntegerField(db_index=True, default=None, help_text='ID da organização no sistema de autenticação', null=True)),
                ('user_id', models.IntegerField(db_index=True, default=None, help_text='ID do usuário no sistema de autenticação', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Data e hora em que a instância foi deletada (soft delete)', null=True, verbose_name='Deletado em')),
                ('deleted_by_id', models.IntegerField(blank=True, help_text='Usuário que deletou a instância (soft delete)', null=True, verbose_name='Deletado por')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Motivo de Vistoria',
                'verbose_name_plural': 'Motivos de Vistoria',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inspection',
            name='motive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='inspection.inspectionmotive'),
        ),
    ]
