# Generated by Django 5.2.4 on 2026-07-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0005_inspectionmotive_inspection_motive'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionmotive',
            name='expiration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionmotive',
            name='expiration_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
