# Generated by Django 5.2.4 on 2026-07-13 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0007_remove_inspection_expiration_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectiontype',
            name='motive',
        ),
    ]
