# Generated by Django 5.2.4 on 2026-07-13 15:15

import inspection.models.step
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0008_remove_inspectiontype_motive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionstep',
            name='photo',
        ),
        migrations.AddField(
            model_name='inspectionstep',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=inspection.models.step.step_file_upload_to),
        ),
    ]
