# Generated by Django 5.2.4 on 2026-07-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0009_remove_inspectionstep_photo_inspectionstep_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='notify_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspection',
            name='notify_whatsapp',
            field=models.BooleanField(default=False),
        ),
    ]
