# Generated by Django 5.2.4 on 2026-07-14 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inspection",
            "0010_inspection_notify_email_inspection_notify_whatsapp",
        ),
        ("message", "__first__"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspectiontype",
            name="provider",
            field=models.CharField(
                blank=True, default="sga", max_length=50, null=True
            ),
        ),
        migrations.CreateModel(
            name="Inspector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization_id",
                    models.IntegerField(
                        db_index=True,
                        default=None,
                        help_text="ID da organização no sistema de autenticação",
                        null=True,
                    ),
                ),
                (
                    "user_id",
                    models.IntegerField(
                        db_index=True,
                        default=None,
                        help_text="ID do usuário no sistema de autenticação",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspectors",
                        to="message.contact",
                    ),
                ),
                (
                    "inspection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspector",
                        to="inspection.inspection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inspetor",
                "verbose_name_plural": "Inspetores",
            },
        ),
    ]
