# Generated by Django 5.2.4 on 2026-07-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inspection", "0011_inspectiontype_provider_inspector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspectiontype",
            name="provider",
            field=models.CharField(
                blank=True,
                choices=[("sga", "SGA")],
                default="sga",
                max_length=50,
                null=True,
            ),
        ),
    ]
