# Generated by Django 5.2.4 on 2026-07-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0012_alter_inspectiontype_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionstep',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionstep',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
