# Generated by Django 5.2.4 on 2026-07-15 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inspection", "0013_inspectionstep_latitude_inspectionstep_longitude"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inspection",
            name="scheduled_to",
        ),
    ]
