# Generated by Django 5.2.4 on 2026-07-17 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inspection", "0014_remove_inspection_scheduled_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspectionstep",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("realized", "Realizada"),
                    ("rejected", "Reprovada"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TorryTechQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization_id",
                    models.IntegerField(
                        db_index=True,
                        default=None,
                        help_text="ID da organização no sistema de autenticação",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Data e hora em que a instância foi deletada (soft delete)",
                        null=True,
                        verbose_name="Deletado em",
                    ),
                ),
                (
                    "deleted_by_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Usuário que deletou a instância (soft delete)",
                        null=True,
                        verbose_name="Deletado por",
                    ),
                ),
                (
                    "plate",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                (
                    "chassi",
                    models.CharField(
                        blank=True, db_index=True, max_length=30, null=True
                    ),
                ),
                ("cons", models.CharField(default="83", max_length=10)),
                ("uf", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "id_pesquisa",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "status_consulta",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("success", models.BooleanField(default=False)),
                ("message", models.TextField(blank=True, null=True)),
                ("response_data", models.JSONField(blank=True, null=True)),
                (
                    "link_impressao",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "inspection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="torry_tech_queries",
                        to="inspection.inspection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consulta Torry Tech",
                "verbose_name_plural": "Consultas Torry Tech",
                "ordering": ["-created_at"],
            },
        ),
    ]
