# Generated by Django 5.2.4 on 2026-07-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inspection", "0015_alter_inspectionstep_status_torrytechquery"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspectionstep",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
