# Generated by Django 5.2.4 on 2026-07-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inspection", "0016_inspectionstep_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspection",
            name="status",
            field=models.CharField(
                choices=[
                    ("emitted", "Emitida"),
                    ("viewed", "Visualizada"),
                    ("performed", "Realizada"),
                    ("approved", "Aprovada"),
                    ("rejected", "Reprovada"),
                    ("expired", "Expirada"),
                ],
                default="emitted",
                max_length=20,
            ),
        ),
    ]
