# Generated by Django 5.2.4 on 2026-07-22 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inspection", "0018_inspection_signature_hash_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivatorAutomationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization_id",
                    models.IntegerField(
                        db_index=True,
                        default=None,
                        help_text="ID da organização no sistema de autenticação",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Data e hora em que a instância foi deletada (soft delete)",
                        null=True,
                        verbose_name="Deletado em",
                    ),
                ),
                (
                    "deleted_by_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Usuário que deletou a instância (soft delete)",
                        null=True,
                        verbose_name="Deletado por",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("emitted", "Vistoria Emitida"),
                            ("approved", "Vistoria Aprovada"),
                            ("signature_created", "Termo Gerado"),
                            ("signature_signed", "Termo Assinado"),
                            ("signature_approved", "Assinatura Aprovada"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "target_situation_code",
                    models.IntegerField(
                        help_text="Código da situação no Ativador (ex: 19 - Aguardando Fotos, 30 - Aprovado p/ Correção, 24 - Pendente Assinatura, 26 - Assinado)"
                    ),
                ),
                (
                    "observation_template",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "inspection_motive",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activator_rules",
                        to="inspection.inspectionmotive",
                    ),
                ),
                (
                    "inspection_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activator_rules",
                        to="inspection.inspectiontype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regra de Automação do Ativador",
                "verbose_name_plural": "Regras de Automação do Ativador",
                "ordering": ["-created_at"],
            },
        ),
    ]
