# Generated by Django 5.2.4 on 2026-07-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inspection", "0020_alter_activatorautomationrule_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="activatorautomationrule",
            name="provider",
            field=models.CharField(
                choices=[("ativador", "Ativador (SGA / Autovisto)")],
                default="ativador",
                max_length=50,
            ),
        ),
    ]
