# Generated by Django 5.2.4 on 2026-07-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0022_automationrule_delete_activatorautomationrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrule',
            name='target_situation_name',
            field=models.CharField(blank=True, default='', help_text='Nome da situação no Ativador/SGA', max_length=255),
        ),
    ]
